site_name: Kotlin Native binding for Godot
docs_dir: src/doc

repo_name: 'raniejade/godot-kotlin'
repo_url: 'https://github.com/raniejade/godot-kotlin'

theme:
  name: material
  favicon: assets/img/favicon.ico
  palette:
    primary: indigo
    accent: light-blue
  logo: assets/img/logo.png

extra:
  social:
    - type: 'github'
      link: 'https://github.com/raniejade'
    - type: 'twitter'
      link: 'https://twitter.com/raniejade'

markdown_extensions:
  - codehilite:
      linenums: true
  - pymdownx.inlinehilite
  - admonition


nav:
  - Overview: index.md
  - API differences: api-differences.md
  - Supported platforms: supported-platforms.md
  - Setting up:
      - Gradle: setup/gradle.md
      - IDE: setup/ide.md
      - Editor plugin: setup/editor-plugin.md
  - User guide:
    - Classes: user-guide/classes.md
    - Methods: user-guide/methods.md
    - Signals: user-guide/signals.md
    - Properties: user-guide/properties.md
  - Release notes: release-notes.md
  - Roadmap: roadmap.md