name: Check PR - godot-kotlin-gradle-plugin
on:
  pull_request:
    paths:
      - 'godot-kotlin-gradle-plugin/**'
      - 'build.gradle.kts'
      - 'buildSrc/build.gradle.kts'
      - 'gradle.properties'
      - '.github/workflows/check-pr-gradle-plugin.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: godot-kotlin-gradle-plugin:build
