name: Check PR - godot-kotlin-editor-plugin
on:
  pull_request:
    paths:
      - 'godot-kotlin-editor-plugin/**'
      - 'build.gradle.kts'
      - 'buildSrc/build.gradle.kts'
      - 'gradle.properties'
      - '.github/workflows/check-pr-editor-plugin.yaml'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            task: buildPluginLinux
          - os: macos-latest
            task: buildPluginMacos
          - os: windows-latest
            task: buildPluginWindows
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: godot-kotlin-editor-plugin
          arguments: ${{ matrix.task }} -PexcludeIdePlugins
