name: Check PR
on: [pull_request]
jobs:
  build_core:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: linux-latest
            build_task: compileKotlinLinuxX64
          - os: windows-latest
            build_task: compileKotlinWindowsX64
          - os: macos-latest
            build_task: compileKotlinMacosX64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Execute gradle build
        run: ./gradlew core:${{ matrix.build_task }}

  build_gradle_plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Execute gradle build
        run: ./gradlew gradle-plugin:build