name: CI
on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  deploy_core:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: godot-kotlin:bintrayUpload -PexcludeIdePlugins
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}

  deploy_editor_plugin:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: godot-kotlin-editor-plugin
          arguments: bintrayUpload -PexcludeIdePlugins
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}

  deply_ij_plugin:
    strategy:
      matrix:
        idea_product: [IJ193]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: godot-kotlin-idea-plugin:publishPlugin -Pidea.product=${{ matrix.idea_product }}
        env:
          HUB_API_TOKEN: ${{ secrets.HUB_API_TOKEN }}

  deploy_gradle_plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: godot-kotlin-gradle-plugin:bintrayUpload -PexcludeIdePlugins
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
